#!/bin/bash
# add colors definitions 
. colours
YT='yt-dlp'

# get url, $1 - youtube uri
#
if [[ -z $2 ]]; then
	echo -e ${NC} "usage \n ${BLUE} getaudio youtube_url outfile.mp3"${NC}
	exit

fi
$YT -g $1 > t
a=$(tail -n 1 t)
rm t
ffmpeg -i $a $2
