#!/bin/bash
. ~/bin/colours
# make mp4 from png
# TODO fix addition of audio.
if [[ -z $3 ]]; then
echo -e "Usage:\n${BLUE}makez inputpic outputvideo durariontime"${NC}
echo -e "Example:\n${BLUE}makez pic.png out.mp4 4"${NC}
exit
fi

ffmpeg -loop 1 -i $1 -t $3 -pix_fmt yuv420p  -y  tmp.mp4
ffmpeg -i tmp.mp4 -i $sec -map 0:v -map 1:a -y $2
rm tmp.mp4
